//@Paulo Ribeiro Marinho
package javaapplication1;

/**
 *
 * @author p7
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Usuarios = new javax.swing.JButton();
        PerfisDeCandidatos = new javax.swing.JButton();
        Empregadores = new javax.swing.JButton();
        VagasDeEmprego = new javax.swing.JButton();
        ParticipaEmProgramas = new javax.swing.JButton();
        ProgramasDeSuporte = new javax.swing.JButton();
        RecursosEducacionais = new javax.swing.JButton();
        EventosEWorkshops = new javax.swing.JButton();
        HistoricoDeAtividades = new javax.swing.JButton();
        Feedback = new javax.swing.JButton();
        SolicitAssistencia = new javax.swing.JButton();
        Candidaturas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Usuarios.setText("Usuários");
        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });

        PerfisDeCandidatos.setText("Perfis de Candidatos");
        PerfisDeCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfisDeCandidatosActionPerformed(evt);
            }
        });

        Empregadores.setText("Empregadores");
        Empregadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpregadoresActionPerformed(evt);
            }
        });

        VagasDeEmprego.setText("Vagas de Emprego");
        VagasDeEmprego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VagasDeEmpregoActionPerformed(evt);
            }
        });

        ParticipaEmProgramas.setText("Participações em Programas");
        ParticipaEmProgramas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParticipaEmProgramasActionPerformed(evt);
            }
        });

        ProgramasDeSuporte.setText("Programas de Suporte");
        ProgramasDeSuporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramasDeSuporteActionPerformed(evt);
            }
        });

        RecursosEducacionais.setText("Recursos Educacionais");
        RecursosEducacionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecursosEducacionaisActionPerformed(evt);
            }
        });

        EventosEWorkshops.setText("Eventos e Workshops");
        EventosEWorkshops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventosEWorkshopsActionPerformed(evt);
            }
        });

        HistoricoDeAtividades.setText("Histórico de Atividades");
        HistoricoDeAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoricoDeAtividadesActionPerformed(evt);
            }
        });

        Feedback.setText("Feedback de Vagas");
        Feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbackActionPerformed(evt);
            }
        });

        SolicitAssistencia.setText("Solicitações de Assistência");
        SolicitAssistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitAssistenciaActionPerformed(evt);
            }
        });

        Candidaturas.setText("Candidaturas");
        Candidaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidaturasActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/IMG/LogoTrampoConnect-removebg-preview.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Bem Vindo!");

        jPanel1.setBackground(new java.awt.Color(64, 49, 49));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Candidaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ParticipaEmProgramas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SolicitAssistencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ProgramasDeSuporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HistoricoDeAtividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Feedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RecursosEducacionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EventosEWorkshops, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Usuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PerfisDeCandidatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Empregadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VagasDeEmprego, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PerfisDeCandidatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Empregadores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VagasDeEmprego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Candidaturas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProgramasDeSuporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ParticipaEmProgramas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HistoricoDeAtividades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Feedback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SolicitAssistencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RecursosEducacionais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EventosEWorkshops)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        // TODO add your handling code here:
        TelaVisualizarUsuarios USUARIOS = new TelaVisualizarUsuarios();
        USUARIOS.setVisible(true);
    }//GEN-LAST:event_UsuariosActionPerformed

    private void PerfisDeCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfisDeCandidatosActionPerformed
        // TODO add your handling code here:
        TelaVisualizarCandidaturas CANDIDATURA = new TelaVisualizarCandidaturas();
        CANDIDATURA.setVisible(true);
    }//GEN-LAST:event_PerfisDeCandidatosActionPerformed

    private void EmpregadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpregadoresActionPerformed
        // TODO add your handling code here:
        TelaVisualizarEmpregadores EMPREGO = new TelaVisualizarEmpregadores();
        EMPREGO.setVisible(true);
    }//GEN-LAST:event_EmpregadoresActionPerformed

    private void VagasDeEmpregoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VagasDeEmpregoActionPerformed
        // TODO add your handling code here:
        TelaVisualizarVagasDeEmprego VAGEMPREGO = new TelaVisualizarVagasDeEmprego();
        VAGEMPREGO.setVisible(true);
    }//GEN-LAST:event_VagasDeEmpregoActionPerformed

    private void ProgramasDeSuporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramasDeSuporteActionPerformed
        // TODO add your handling code here:
        TelaVisualizarProgramasDeSuporte PROGSUP = new TelaVisualizarProgramasDeSuporte();
        PROGSUP.setVisible(true);
    }//GEN-LAST:event_ProgramasDeSuporteActionPerformed

    private void EventosEWorkshopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventosEWorkshopsActionPerformed
        // TODO add your handling code here:
        TelaVisualizarEventos EVENTOS = new TelaVisualizarEventos();
        EVENTOS.setVisible(true);
    }//GEN-LAST:event_EventosEWorkshopsActionPerformed

    private void RecursosEducacionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecursosEducacionaisActionPerformed
        // TODO add your handling code here:
        TelaVisualizarRecursosEducacionais RECEDUC = new TelaVisualizarRecursosEducacionais();
        RECEDUC.setVisible(true);
    }//GEN-LAST:event_RecursosEducacionaisActionPerformed

    private void ParticipaEmProgramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParticipaEmProgramasActionPerformed
        // TODO add your handling code here:
        TelaVisualizarParticipacaoEventos PARTICIPEVNT = new TelaVisualizarParticipacaoEventos();
        PARTICIPEVNT.setVisible(true);
    }//GEN-LAST:event_ParticipaEmProgramasActionPerformed

    private void HistoricoDeAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoricoDeAtividadesActionPerformed
        // TODO add your handling code here:
        TelaVisualizarHistoricoAtividades HISTATIV = new TelaVisualizarHistoricoAtividades();
        HISTATIV.setVisible(true);
    }//GEN-LAST:event_HistoricoDeAtividadesActionPerformed

    private void FeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbackActionPerformed
        // TODO add your handling code here:
        TelaVisualizarFeedback FEEDBACK = new TelaVisualizarFeedback();
        FEEDBACK.setVisible(true);
    }//GEN-LAST:event_FeedbackActionPerformed

    private void SolicitAssistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitAssistenciaActionPerformed
        // TODO add your handling code here:
        TelaVisualizarSolicitacoes SOLICITACOES = new TelaVisualizarSolicitacoes();
        SOLICITACOES.setVisible(true);
    }//GEN-LAST:event_SolicitAssistenciaActionPerformed

    private void CandidaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidaturasActionPerformed
        // TODO add your handling code here:
        TelaVisualizarCandidaturas CAND = new TelaVisualizarCandidaturas();
        CAND.setVisible(true);
    }//GEN-LAST:event_CandidaturasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Candidaturas;
    private javax.swing.JButton Empregadores;
    private javax.swing.JButton EventosEWorkshops;
    private javax.swing.JButton Feedback;
    private javax.swing.JButton HistoricoDeAtividades;
    private javax.swing.JButton ParticipaEmProgramas;
    private javax.swing.JButton PerfisDeCandidatos;
    private javax.swing.JButton ProgramasDeSuporte;
    private javax.swing.JButton RecursosEducacionais;
    private javax.swing.JButton SolicitAssistencia;
    private javax.swing.JButton Usuarios;
    private javax.swing.JButton VagasDeEmprego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
